os: Visual Studio 2017

clone_depth: 100

cache:
    - C:\.hunter -> .appveyor.yml

environment:
    global:
        BOOST_ROOT: "C:/Libraries/boost_1_70_0"
        BOOST_LIBRARYDIR: "C:/Libraries/boost_1_70_0/lib64-msvc-14.1"
        Qt5_DIR: "C:/Qt/5.12/msvc2017_64/lib/cmake/Qt5"
    matrix:
        - Purpose: "WindowsDebugBuild"
          DEC_GENERATOR_NAME: "Visual Studio 15 2017 Win64"
          DEC_BUILD_TYPE: "Debug"
          DEC_TOOLCHAIN_FILE_NAME: "cmake/polly/vs-15-2017-win64.cmake"
          DEC_TESTS_REGEXP: "NONE"
        - Purpose: "WindowsReleaseBuild"
          DEC_GENERATOR_NAME: "Visual Studio 15 2017 Win64"
          DEC_BUILD_TYPE: "Release"
          DEC_TOOLCHAIN_FILE_NAME: "cmake/polly/vs-15-2017-win64.cmake"
          DEC_TESTS_REGEXP: "NONE"

install:
    - git submodule update --init --recursive

build_script:
    - md build
    - cd build
    - >
        cmake -G "%DEC_GENERATOR_NAME%"
        -DCMAKE_BUILD_TYPE=%DEC_BUILD_TYPE%
        -DCMAKE_TOOLCHAIN_FILE=%DEC_TOOLCHAIN_FILE_NAME%
        -DBUILD_ALL:BOOL=TRUE
        ..
    - cmake --build . --config %DEC_BUILD_TYPE%
    - ctest -C %DEC_BUILD_TYPE% -R "%DEC_TESTS_REGEXP%" -V -j 2
    - cpack -C %DEC_BUILD_TYPE%

artifacts:
    - path: build\*\deocoin-gui-*.exe
      name: Releases

deploy:
    description: "Deocoin GUI release"
    provider: GitHub
    auth_token:
        secure: "2+Ji3AkIi/6n3bNzeQNvr7ZKetnvNC/K5czk1iDU5OQHiozVan1ksMw3Nk1GTssO"
    artifact: /deocoin-gui-.*\.exe/
    draft: true
    prerelease: true
    on:
        APPVEYOR_REPO_TAG: true
        DEC_BUILD_TYPE: "Release"
