language: cpp

matrix:
    include:
        - name: "Linux, Debug"
          os: linux
          dist: xenial
          sudo: required
          env:
              - CMAKE_GENERATOR_NAME="Unix Makefiles"
              - CMAKE_BUILD_TYPE="Debug"
              - CMAKE_TOOLCHAIN_FILE_NAME=gcc-cxx14-c11.cmake
              - Qt5_DIR="/opt/qt512/lib/cmake/Qt5"
        - name: "Linux, Release"
          os: linux
          dist: xenial
          sudo: required
          env:
              - CMAKE_GENERATOR_NAME="Unix Makefiles"
              - CMAKE_BUILD_TYPE="Release"
              - CMAKE_TOOLCHAIN_FILE_NAME=gcc-cxx14-c11.cmake
              - Qt5_DIR="/opt/qt512/lib/cmake/Qt5"
        - name: "macOS, Debug"
          os: osx
          osx_image: xcode11.3
          env:
              - CMAKE_GENERATOR_NAME="Unix Makefiles"
              - CMAKE_BUILD_TYPE="Debug"
              - CMAKE_TOOLCHAIN_FILE_NAME=clang-cxx14.cmake
              - Qt5_DIR="/usr/local/opt/qt/lib/cmake/Qt5"
        - name: "macOS, Release"
          os: osx
          osx_image: xcode11.3
          env:
              - CMAKE_GENERATOR_NAME="Unix Makefiles"
              - CMAKE_BUILD_TYPE="Release"
              - CMAKE_TOOLCHAIN_FILE_NAME=clang-cxx14.cmake
              - Qt5_DIR="/usr/local/opt/qt/lib/cmake/Qt5"

addons:
    apt: # Linux
        packages:
            - build-essential
            - cmake
            - git
            - libgl1-mesa-dev
            - qt512-meta-full
            - unzip
            - wget
            - rpm
        sources:
            - ubuntu-toolchain-r-test
            - sourceline: "ppa:beineri/opt-qt-5.12.3-xenial"
    homebrew: # macOS
        packages:
            - cmake
            - git
            - qt5

cache:
    directories:
        - $HOME/.hunter

script:
    - mkdir ./build && cd ./build
    - >
        cmake -G "$CMAKE_GENERATOR_NAME"
        -DCMAKE_BUILD_TYPE=$CMAKE_BUILD_TYPE
        -DCMAKE_TOOLCHAIN_FILE=cmake/polly/$CMAKE_TOOLCHAIN_FILE_NAME
        -DBUILD_ALL:BOOL=TRUE
        ..
    - cmake --build . --config $CMAKE_BUILD_TYPE -- -j 2
    - cpack -C $CMAKE_BUILD_TYPE

deploy:
    provider: releases # GitHub Releases
    api_key:
        secure: "OOPZ+YOZRNOLjj/B9EQZqXiV+D+xM9Nc2bz2wSXP58TS0kc1N1XvrLH/bKPsV1KGziYAZvm/PDH1+xdyH/aW48jLxmCrzxwqhUoL+rwYhSZVXsV5JLWeJuC6TtdrJUIGen7E3K8lTht5GicLaQdPtEN+wZgIjFDOBFUJiip0hAe867U8M3Tmpy+azBP6uRTijHGCxaFGnf93bLPeGzSaNk2nVzoA8xsALeEj0BUum9vRuzPGvQJeQqTrPYWWG9qaNmY6pDyrX1o7xS2Fxk0Rljglv4tw/feTe9r4PJvX429gnpd87PoV07aLauxkgwA0PmOguco7syHCZI2IAR9w35lZIlwhFngjQGCZlzPjNtckyCQxIR8PULDNbx5wPUnvQjM0Y+79G7qiz1ueJfiv0GSk4M0S/fcaRH6X5qJlZu4eHzCNCqc86rjeykAdWmCv6Rm7dHnKMlBMZEFhlyGESynFhFLwk0eExONTlQ7Db9Ol9/eXz3kKIbzOHnnr3bltlRU086gCr8e5zy4021T0QIBORuPJiyoZYGppRiF3aEGlB+8fRE05evAvHRt4KXcNodbkdOxAZ/mmZjPw28G0vUtftFxWXpt9XPsGnkhZryAqCnsGbcBACOEdjEHEhqV95DXRi7mL/liqbRx6ZnDVKQNQRzyFdGi28it6ihffB/w="
    file: dist/deocoin-gui-* # path is relative to the current working directory, not to $TRAVIS_BUILD_DIR
    file_glob: true
    draft: true
    on:
        branch: master
        tags: true
        condition: $CMAKE_BUILD_TYPE = "Release"
    skip_cleanup: true