name: Release

on:
  push:
    tags:
    - '*'

jobs:
  build-windows:
    name: Windows
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 0

      - name: Setup MSBuild.exe
        uses: microsoft/setup-msbuild@v1

      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:
          version: '5.12.2'
          host: 'windows'
          target: 'desktop'
          modules: 'qttools5'
          install-deps: 'true'

      - name: Install NSIS
        uses: joncloud/makensis-action@v1
        with:
          just-include: true

      - name: Build
        shell: powershell
        id: build
        env:
          BOOST_ROOT: ${{ env.BOOST_ROOT }}
        run: |
          $build_folder = "build"
          $qwc_ver = "${{ github.ref }}" -replace '[refs/tags/]'
          $release_name = "Deocoin-wallet-win64-$qwc_ver"
          set CMAKE_PREFIX_PATH="$($qt5_cmake)"
          $qt5_cmake = "${{ env.Qt5_Dir }}/lib/cmake" -replace '[/]', '\\'
          mkdir "$build_folder"
          cd "$build_folder"
          Start-Process cmake -ArgumentList "-DBOOST_ROOT=""$env:BOOST_ROOT_1_69_0"" -G ""Visual Studio 16 2019"" -DBUILD_ALL:BOOL=""TRUE"" -A x64",".." -NoNewWindow -Wait
          Start-Process msbuild -ArgumentList "Deocoin-GUI.sln","/p:Configuration=Release" -NoNewWindow -Wait
          $build_path = "./$build_folder"
          echo "::set-output name=build_path::${build_path}"
          echo "::set-output name=release_name::${release_name}"
          echo "::set-output name=qwc_ver::${qwc_ver}"
          echo "${Qt5_Dir}"
  
      - name: Pack
        shell: powershell
        id: pack
        env:
          VCINSTALLDIR: 'C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\'
        run: |
          $build_folder = "${{ steps.build.outputs.build_path }}"
          $release_name = "${{ steps.build.outputs.release_name }}"
          $release_folder = "Release"
          cd "$build_folder"
          $qwc_ver = "${{ steps.build.outputs.qwc_ver }}"
          mkdir "$release_folder/$release_name"
          cd "$release_folder"
          cp Deocoin-GUI.exe "$release_name/"
          cp "../../LICENSE.txt" "$release_name/LICENSE.txt"
          windeployqt --release Deocoin-GUI.exe --dir "$release_name/"
          Compress-Archive -Path "$release_name/" -DestinationPath "$release_name.zip"
          $sha256a = (Get-FileHash "$release_name.zip").Hash
          $asset_path_archive = "./$build_folder/$release_folder/$release_name.zip"
          echo "::set-output name=sha256a::${sha256a}"
          echo "::set-output name=release_name_archive::${release_name}.zip"
          echo "::set-output name=asset_path_archive::${asset_path_archive}"
          cd ../
          makensis WindowsInstall.nsi
          cd "$release_folder"
          Compress-Archive -Path "Deocoin-GUI-Setup.exe" -DestinationPath "$release_name-install.zip"
          $sha256i = (Get-FileHash "$release_name-install.zip").Hash
          $asset_path_install = "./$build_folder/$release_folder/$release_name-install.zip"
          echo "::set-output name=sha256i::${sha256i}"
          echo "::set-output name=release_name_install::${release_name}-install.zip"
          echo "::set-output name=asset_path_install::${asset_path_install}"
          echo "::set-output name=qwc_ver::${qwc_ver}"

      - name: Create Release Archive
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ steps.pack.outputs.asset_path_archive }}
          name: Deocoin Wallet ${{ steps.pack.outputs.qwc_ver }}
          body: |
            **${{ steps.pack.outputs.release_name_archive }}**
            ${{ steps.pack.outputs.sha256a }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Release Installer
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ steps.pack.outputs.asset_path_install }}
          name: Deocoin Wallet ${{ steps.pack.outputs.qwc_ver }}
          body: |
            **${{ steps.pack.outputs.release_name_install }}**
            ${{ steps.pack.outputs.sha256i }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-macos:
    name: macOS
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 0

      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '10'

      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:
          version: '5.12.2'
          modules: 'qttools5'
          install-deps: 'true'

      - name: Build
        id: build
        run: |
          build_folder="build/release"
          qwc_ver=$(echo ${{ github.ref }} | sed 's|refs/tags/||')
          release_name="Deocoin-wallet-macOS-$qwc_ver"
          app_name="Deocoin-GUI.app"
          lang_folder="/Contents/Resources/languages"
          brew install gcc boost
          brew link boost --force
          mkdir -p "$build_folder"
          cd "$build_folder"
          cmake -DCMAKE_C_FLAGS="-mmacosx-version-min=10.12" -DBUILD_ALL:BOOL=TRUE -DCMAKE_CXX_FLAGS="-mmacosx-version-min=10.12" -D CMAKE_BUILD_TYPE=Release ../..
          make
          mkdir "$app_name$lang_folder"
          cp languages/*.qm "$app_name$lang_folder"
          macdeployqt "$app_name"
          cpack
          mv *.dmg "$release_name".dmg
          sha256=$(shasum -a 256 "$release_name".dmg | awk '{ print toupper($1) }')
          asset_path="./$build_folder/$release_name.dmg"
          echo "::set-output name=sha256::${sha256}"
          echo "::set-output name=release_name::${release_name}.zip"
          echo "::set-output name=asset_path::${asset_path}"
          echo "::set-output name=qwc_ver::${qwc_ver}"

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ steps.build.outputs.asset_path }}
          name: Deocoin Wallet ${{ steps.build.outputs.qwc_ver }}
          body: |
            **${{ steps.build.outputs.release_name }}**
            ${{ steps.build.outputs.sha256 }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-ubuntu20:
    name: Ubuntu 20.04
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 0

      - name: Build
        id: build
        run: |
          sudo apt update -y
          sudo apt install -y qt5-default qttools5-dev qttools5-dev-tools libboost-all-dev
          build_folder="build/release"
          qwc_ver=$(echo "$GITHUB_REF" | sed 's|refs/tags/||')
          release_name=Deocoin-wallet-ubuntu-20.04-"$qwc_ver"
          app_name="Deocoin-GUI"
          mkdir -p "$build_folder"
          cd "$build_folder"
          cmake -D ARCH=default -D CMAKE_BUILD_TYPE=Release -D BUILD_ALL:BOOL=true -D CMAKE_POSITION_INDEPENDENT_CODE:BOOL=true -D BOOST_IGNORE_SYSTEM_PATHS_DEFAULT=ON -D BOOST_ROOT=/usr ../..
          make
          cpack
          tar -czf "$release_name".tar.gz *.deb
          sha256=$(shasum -a 256 "$release_name".tar.gz | awk '{print toupper($1)}')
          asset_path="./$build_folder/$release_name".tar.gz
          echo "::set-output name=sha256::${sha256}"
          echo "::set-output name=release_name::${release_name}.tar.gz"
          echo "::set-output name=asset_path::${asset_path}"
          echo "::set-output name=qwc_ver::${qwc_ver}"

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ steps.build.outputs.asset_path }}
          name: Deocoin Wallet ${{ steps.build.outputs.qwc_ver }}
          body: |
            **${{ steps.build.outputs.release_name }}**
            ${{ steps.build.outputs.sha256 }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-ubuntu18:
    name: Ubuntu 18.04
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 0

      - name: Build
        id: build
        run: |
          sudo apt-get purge '*boost*'
          sudo apt update -y
          sudo apt install -y qt5-default qttools5-dev qttools5-dev-tools libboost1.62-all-dev
          build_folder="build/release"
          qwc_ver=$(echo "$GITHUB_REF" | sed 's|refs/tags/||')
          release_name=Deocoin-wallet-ubuntu-18.04-"$qwc_ver"
          app_name="Deocoin-GUI"
          mkdir -p "$build_folder"
          cd "$build_folder"
          cmake -D ARCH=default -D CMAKE_BUILD_TYPE=Release -D BUILD_ALL:BOOL=TRUE -D CMAKE_POSITION_INDEPENDENT_CODE:BOOL=true -D BOOST_IGNORE_SYSTEM_PATHS_DEFAULT=ON -D BOOST_ROOT=/usr ../..
          make
          cpack
          tar -czf "$release_name".tar.gz *.deb
          sha256=$(shasum -a 256 "$release_name".tar.gz | awk '{print toupper($1)}')
          asset_path="./$build_folder/$release_name".tar.gz
          echo "::set-output name=sha256::${sha256}"
          echo "::set-output name=release_name::${release_name}.tar.gz"
          echo "::set-output name=asset_path::${asset_path}"
          echo "::set-output name=qwc_ver::${qwc_ver}"

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ steps.build.outputs.asset_path }}
          name: Deocoin Wallet ${{ steps.build.outputs.qwc_ver }}
          body: |
            **${{ steps.build.outputs.release_name }}**
            ${{ steps.build.outputs.sha256 }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

